[build]
target = "xtensa-esp32s3-espidf"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor --log-format defmt"
# runner = "probe-rs run --chip esp32s3"
rustflags = [
	"--cfg",
	"espidf_time64",
] # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "esp32s3"
DEFMT_LOG = "debug"
ESP_IDF_PATH_ISSUES = "warn"
CRATE_CC_NO_DEFAULTS = "1"
