[keyboard]
name = "CursedKeeb"
product_name = "CursedKeeb"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "dzervas"
chip = "nrf52840"
usb_enable = true

[matrix]
# Input and output pins are mandatory
input_pins = ["P0_02", "P0_03", "P0_28"]
output_pins = ["MI20_A0", "MI20_A1", "MI20_A2", "MI20_A3"]
# output_pins = ["P1_02", "P1_03", "P1_04", "P1_05"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true

[layout]
rows = 4
cols = 3
layers = 1
keymap = [
	[
		[
			"A",
			"B",
			"C",
		],
		[
			"D",
			"E",
			"F",
		],
		[
			"G",
			"H",
			"I",
		],
		[
			"J",
			"K",
			"L",
		],
	],
]

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "P0_30"
# capslock.low_active = false
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true

[storage]
# Storage feature is enabled by default
# enabled = false

[ble]
enabled = true
# battery_adc_pin = "vddh"
# charge_state.pin = "P0_25"
# charge_state.low_active = false
# charge_led.pin = "P0_29"
# charge_led.low_active = false

[gpio]
mcp23017_enabled = true
i2c_enabled = true
i2c_sda = "P0_04"
i2c_scl = "P0_05"
i2c_freq_khz = 100
